apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: instavote
  labels:
    role: vote
spec:
  selector:
    role: vote
    #version: v2
  ports:
    - name: pythonapp
      port: 80
      targetPort: 80
      nodePort: 32760
  type: NodePort
