---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: db
    tier: back
  name: db
  namespace: instavote
spec:
  selector:
    role: database
  ports:
    - port: 5432
      targetPort: 5432
