apiVersion: v1
kind: Service
metadata:
  name: results
  namespace: instavote
  labels:
    role: results
spec:
  selector:
    role: results
  ports:
    - port: 81
      #targetPort: 8080
      targetPort: 80
      nodePort: 32761
  type: NodePort
